{
 "title": "Pool",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Links",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "[Pool Stats](/d/ad4559x/pool) | [Users and Workers](/d/adnhx6x/users-and-workers) | [Hydrapool Github](https://github.com/256-Foundation/Hydrapool)\n\n"
   }
  },
  {
   "title": "Pool Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(shares_accepted_total[5m])",
     "legendFormat": "Pool Hashrate (5m)"
    },
    {
     "expr": "rate(shares_accepted_total[1h])",
     "legendFormat": "Pool Hashrate (1h)"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count((sum by (btcaddress) (rate(worker_shares_valid_total[5m])) > 0))",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "count((sum by (btcaddress, workername) (rate(worker_shares_valid_total[5m])) > 0))",
     "legendFormat": "Workers"
    }
   ]
  },
  {
   "title": "Coinbase Rewards (sats)",
   "type": "piechart",
   "description": "Coinbase for the current block being mined by the pool. This reflects the results of the PPLNS computation where work submitted by each user is taken into account to distribute the reward. This also shows any donation or fees used by the pool operator.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "coinbase_output", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Hashrate Distribution",
   "type": "piechart",
   "description": "Hashrate distribution over the selected time period. This distribution depends on when the pool started and the time period selected at the top of the dashboard. This is different from the coinbase rewards as that is computed based on the PPLNS rules and does not depend on server restarts or time period selected to view it.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (btcshort) (\n  label_replace(\n    worker_shares_valid_total,\n    \"btcshort\", \"$1...$2\", \"btcaddress\", \"^(....).*(........)$\"\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Best Share Difficulty",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "best_share", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time() - start_time_seconds", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Shares Accepted Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(shares_accepted_total[$__rate_interval])",
     "legendFormat": "Shares per second"
    }
   ]
  },
  {
   "title": "Shares Rejected Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(shares_rejected_total[$__rate_interval])",
     "legendFormat": "Shares per second"
    }
   ]
  }
 ]
}