{
 "title": "矿池统计",
 "tags": [
  "chinese",
  "中文"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "导航链接",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "[矿池统计](/d/ad4559x-zh/pool-zh) | [用户与矿机](/d/adnhx6x-zh/users-zh) | [Hydrapool Github](https://github.com/256-Foundation/Hydra-Pool)\n\n"
   }
  },
  {
   "title": "矿池算力",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(shares_accepted_total[5m])",
     "legendFormat": "矿池算力 (5分钟)"
    },
    {
     "expr": "rate(shares_accepted_total[1h])",
     "legendFormat": "矿池算力 (1小时)"
    }
   ]
  },
  {
   "title": "用户数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count((sum by (btcaddress) (rate(worker_shares_valid_total[5m])) > 0))",
     "legendFormat": "用户数"
    }
   ]
  },
  {
   "title": "矿机数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "count((sum by (btcaddress, workername) (rate(worker_shares_valid_total[5m])) > 0))",
     "legendFormat": "矿机数"
    }
   ]
  },
  {
   "title": "Coinbase 收益（聪）",
   "type": "piechart",
   "description": "当前正在挖掘区块的 Coinbase 分配。反映了 PPLNS 计算结果，根据每个用户提交的工作量来分配奖励。同时显示矿池运营商设置的捐赠或费用。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "coinbase_output", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "算力分布",
   "type": "piechart",
   "description": "选定时间段内的算力分布。此分布取决于矿池启动时间和面板顶部选择的时间段。与 Coinbase 收益不同，后者基于 PPLNS 规则计算，不受服务器重启或时间段选择的影响。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (btcshort) (\n  label_replace(\n    worker_shares_valid_total,\n    \"btcshort\", \"$1...$2\", \"btcaddress\", \"^(....).*(........)$\"\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "最佳 Share 难度",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "best_share", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time() - start_time_seconds", "legendFormat": "运行时间" }
   ]
  },
  {
   "title": "每秒接收 Shares",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(shares_accepted_total[$__rate_interval])",
     "legendFormat": "每秒接收 Shares"
    }
   ]
  },
  {
   "title": "每秒拒绝 Shares",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(shares_rejected_total[$__rate_interval])",
     "legendFormat": "每秒拒绝 Shares"
    }
   ]
  }
 ]
}