{
 "title": "用户与矿机（私有）",
 "tags": [
  "chinese",
  "中文"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "user_address", "label": "用户 BTC 地址" },
   {
    "name": "workername",
    "label": "矿机名称",
    "query": {
     "query": "label_values(worker_shares_valid_total{btcaddress=\"$user_address\"},workername)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "用户算力",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(btcaddress) (rate(worker_shares_valid_total{btcaddress=\"$user_address\"}[5m]))",
     "legendFormat": "算力 (5分钟)"
    },
    {
     "expr": "sum by(btcaddress) (rate(worker_shares_valid_total{btcaddress=\"$user_address\"}[1h]))",
     "legendFormat": "算力 (1小时)"
    }
   ]
  },
  {
   "title": "矿机算力",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "repeat": "workername",
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(worker_shares_valid_total{btcaddress=\"$user_address\", workername=\"$workername\"}[5m])",
     "legendFormat": "{{workername}} (5分钟)"
    },
    {
     "expr": "rate(worker_shares_valid_total{btcaddress=\"$user_address\", workername=\"$workername\"}[1h])",
     "legendFormat": "{{workername}} (1小时)"
    }
   ]
  },
  {
   "title": "最高难度",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "repeat": "workername",
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_best_share_ever{btcaddress=\"$user_address\", workername=\"$workername\"}",
     "legendFormat": "{{workername}}"
    }
   ]
  }
 ]
}